color0 #111415
color1 #ffb4ab
color2 #95ceea
color3 #b4cad6
color4 #dfb9ee
color5 #95ceea
color6 #b4cad6
color7 #e1e2e4
color8 #8a9297
color9 #ffb4ab
color10 #95ceea
color11 #b4cad6
color12 #dfb9ee
color13 #95ceea
color14 #b4cad6
color15 #e1e2e4

cursor                #e1e2e4
cursor_text_color     #111415
background            #111415
foreground            #e1e2e4
selection_foreground  #c0c8cd
selection_background  #40484c
active_border_color   #95ceea
inactive_border_color #40484c
url_color             #95ceea

active_tab_foreground   #003546
active_tab_background   #95ceea
inactive_tab_foreground #c0c8cd
inactive_tab_background #40484c
cursor_trail_color      #c0c8cd
