[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/wx6kw7wqljq1lgyd1c2kyavl9hscd9bp-noctalia-shell-2026-04-03_759454d/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/egor/.cache/noctalia/placeholder.json"

